### ISSUE TITLE
windows version

### ISSUE THREAD

**Issue by rigas40** [drikqlis/SubSyncStarter#1]
is possible made version for windows?
 and add merge subs and video with mkvmerge and output mkv

**Comment by drikqlis** [comment]
I haven't tested it but you could try it on Windows and let me know if there are any errors, maybe we can fix them. 
This is just a simple script to start SubSync, if you want merging subs and remuxing/converting take a look at https://github.com/HaveAGitGat/Tdarr it looks promising and is extendable by plugins.
