### ISSUE TITLE
Double quote escape

### ISSUE THREAD

**Issue by Jorman** [drikqlis/SubSyncStarter#2]
Hi, I think that this line:
`command = "/snap/bin/subsync --cli --verbose " + loglevel_subsync + " --logfile '" + logfile_subsync + "' --window-size " + window_size + " --max-point-dist " + max_point_dist + " sync --sub '" + sub_file + "' --ref '" + reference_file + "' --out '" + sub_file + "' --effort " + effort +" --overwrite"`
Have to be like this:
`command = location_subsync + ' --cli --verbose ' + loglevel_subsync + ' --logfile ' + '"' + logfile_subsync + '"' + ' --window-size ' + window_size + ' --max-point-dist ' + max_point_dist + ' sync --sub ' + '"' + sub_file + '"' + ' --ref ' + '"' + reference_file + '"' + ' --out ' + '"' + sub_file + '"' + ' --effort ' + effort + ' --overwrite'`
Just to escape a possible problem with film or movie with ' on path

**Comment by drikqlis** [comment]
Thanks, fixed in https://github.com/drikqlis/SubSyncStarter/commit/c9b800e42f0d18f6fdbb08d4c554a7555fcb34ff
